name: Investment Ideas React app deployment

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Deploy
            run: |
                 npm install
                 npm run deploy

            
            
